"""Orchestrates applycal to apply/remove/check calibration curves on an ICC profile."""
from __future__ import annotations

import re
from pathlib import Path
from typing import TYPE_CHECKING, Callable

from core.logger import get_logger

if TYPE_CHECKING:
    from core.argyll_runner import ArgyllRunner
    from core.settings import AppSettings

log = get_logger(__name__)


# Errors / warnings that applycal can produce. Line refs target
# Argyll 3.5.0 spectro/profile/applycal.c. Many of the error()s in that file
# are about internal tag-manipulation failures (malloc, internal asserts,
# "Failed to create tag…", "Internal, run out of…") that users will never
# realistically trigger — we surface only the ones with a user-actionable fix.
_APPLYCAL_ERROR_PATTERNS: list[tuple[re.Pattern[str], str, str]] = [
    # L266 / L282 — most common user error: cal and profile aren't the same colour space
    (re.compile(r"Calibration space (\S+) doesn't match profile (\S+)"),
     "space_mismatch",
     "The calibration's colour space ('{0}') doesn't match the profile's "
     "colour space ('{1}').\n\nMake sure the .cal file was created from the "
     "same printer and chart colour space as the ICC profile you're "
     "applying it to."),
    # L292 — can't apply cal to certain profile classes
    (re.compile(r"Can't apply calibration to profile of class (\S+)"),
     "wrong_class",
     "applycal can't apply calibration to a profile of class '{0}'. Pick an "
     "output or input ICC profile instead."),
    # L189 — corrupt or non-ICC file
    (re.compile(r"Unable to read all tags:\s*\d+,\s*(.+)$"),
     "icc_read",
     "The ICC profile couldn't be opened or has corrupt tags.\n\nArgyll "
     "reported: {0}"),
    # L237 / L304 / L348 — missing description tag (typically not a real ICC profile)
    (re.compile(r"Can't find icSigProfileDescriptionTag in profile"),
     "no_desc_tag",
     "The selected file is missing the standard ICC ProfileDescription tag. "
     "It may not be a valid ICC profile."),
    # L173 — error reading the .cal file
    (re.compile(r"new_xcal failed"),
     "cal_read",
     "The calibration (.cal) file could not be loaded. Check that the file "
     "exists and was generated by printcal or chartread."),
]

_APPLYCAL_WARNING_PATTERNS: list[tuple[re.Pattern[str], str, str]] = [
    # L223 — applying output-class cal to input profile
    (re.compile(r"Non-input calibration being applied to an input profile"),
     "non_input_to_input",
     "A non-input calibration is being applied to an input profile — this is "
     "unusual. Double-check that you've picked the right .cal and profile."),
]


class ApplycalRunner:
    def __init__(self, runner: "ArgyllRunner", settings: "AppSettings") -> None:
        self._runner = runner
        self._settings = settings
        self._matched_errors: list[tuple[str, str]] = []
        self._matched_warnings: list[tuple[str, str]] = []

    def run(
        self,
        cal_path: Path,
        in_icc: Path,
        out_icc: Path,
        mode: str,                            # "apply" | "remove" | "check"
        verbose: bool,
        on_line: Callable[[str], None],
        on_finish: Callable[[Path | None], None],
    ) -> None:
        """Run applycal; call on_finish(out_icc) on success, on_finish(None) on failure."""
        args = self._build_args(cal_path, in_icc, out_icc, mode, verbose)
        work_dir = in_icc.parent
        log.info("applycal args: %s", args)
        self._matched_errors = []
        self._matched_warnings = []

        def _scan(line: str) -> None:
            self._scan_line(line)
            on_line(line)

        self._runner.run(
            "applycal",
            args,
            work_dir,
            on_line=_scan,
            on_finish=lambda code: self._done(code, out_icc, mode, on_finish),
        )

    def _scan_line(self, line: str) -> None:
        for pattern, key, fmt in _APPLYCAL_ERROR_PATTERNS:
            m = pattern.search(line)
            if m:
                self._matched_errors.append((key, fmt.format(*m.groups())))
        for pattern, key, fmt in _APPLYCAL_WARNING_PATTERNS:
            m = pattern.search(line)
            if m:
                self._matched_warnings.append((key, fmt.format(*m.groups())))

    def primary_failure(self) -> tuple[str, str] | None:
        return self._matched_errors[0] if self._matched_errors else None

    def captured_warnings(self) -> list[tuple[str, str]]:
        return list(self._matched_warnings)

    def _done(
        self,
        code: int,
        out_icc: Path,
        mode: str,
        on_finish: Callable[[Path | None], None],
    ) -> None:
        if mode == "check":
            # Check mode doesn't write a file; success = exit 0
            on_finish(out_icc if code == 0 else None)
        else:
            success = (code == 0) and out_icc.exists()
            if success:
                log.info("applycal succeeded → %s", out_icc)
                on_finish(out_icc)
            else:
                log.error("applycal failed (code %d)", code)
                on_finish(None)

    @staticmethod
    def _build_args(
        cal_path: Path,
        in_icc: Path,
        out_icc: Path,
        mode: str,
        verbose: bool,
    ) -> list[str]:
        args: list[str] = []
        if verbose:
            args.append("-v")
        if mode == "remove":
            args.append("-u")
        elif mode == "check":
            args.append("-c")
        # "apply" is the default (-a), no flag needed
        args.append(str(cal_path))
        args.append(str(in_icc))
        if mode != "check":
            args.append(str(out_icc))
        return args
