# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for ChromIQ — Windows x64.

Build command (run from the repo root with venv active):
    pyinstaller ChromIQWin.spec

Result: dist/ChromIQ/ChromIQ.exe  (one-dir bundle)
"""

import certifi
from PyInstaller.utils.hooks import collect_all

certifi_where = certifi.where()

_ic_datas, _ic_binaries, _ic_hiddenimports = collect_all('imagecodecs')

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[*_ic_binaries],
    datas=[
        ('assets',               'assets'),
        ('data/parameters.yaml', 'data'),
        (certifi_where,          'certifi'),
        *_ic_datas,
    ],
    hiddenimports=[
        'PyQt6.sip',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'PyQt6.QtPrintSupport',
        'PIL.Image',
        'PIL.ImageFile',
        'PIL.ImageCms',
        'PIL.TiffImagePlugin',
        'yaml',
        'tifffile',
        'numpy',
        *_ic_hiddenimports,
    ],
    hookspath=['hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['cups'],          # pycups is macOS/Linux-only
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='ChromIQ',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    icon='assets/app_icon.ico',  # generated by CI from app_icon.png
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='ChromIQ',
)
